import { existsSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ensureDirectory } from "../../shared/project-context.mjs";

export const INIT_BANNER = "// Generated by Agent Picker init.";
export const GENERATED_BANNER = "// Generated by scripts/generate-agent-picker-drafts.mjs.";

export function toPosix(value) {
  return value.split(path.sep).join("/");
}

export function toRelativeImportPath(fromFile, targetFile) {
  const relativePath = toPosix(path.relative(path.dirname(fromFile), targetFile)).replace(/\.(tsx|ts|jsx|js)$/, "");
  return relativePath.startsWith(".") ? relativePath : `./${relativePath}`;
}

export function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, "utf8"));
}

export function writeJson(filePath, value) {
  ensureDirectory(path.dirname(filePath));
  writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function isManagedContent(content) {
  return content.includes(INIT_BANNER) || content.includes(GENERATED_BANNER);
}

export function writeManagedFile(filePath, content, options = {}) {
  const normalizedContent = `${content.trimEnd()}\n`;
  if (existsSync(filePath)) {
    const existing = readFileSync(filePath, "utf8");
    if (existing === normalizedContent) {
      return false;
    }

    if (!options.force && !isManagedContent(existing)) {
      throw new Error(`Refusing to overwrite existing file without --force: ${filePath}`);
    }
  }

  ensureDirectory(path.dirname(filePath));
  writeFileSync(filePath, normalizedContent, "utf8");
  return true;
}

export function ensureFile(filePath, content) {
  if (existsSync(filePath)) {
    return false;
  }

  ensureDirectory(path.dirname(filePath));
  writeFileSync(filePath, `${content.trimEnd()}\n`, "utf8");
  return true;
}

export function ensureDraftsKeepFile(draftsDirectoryPath, draftsKeepPath) {
  const entries = readdirSync(draftsDirectoryPath).filter((entry) => entry !== ".gitkeep" && !entry.startsWith("."));

  if (entries.length === 0) {
    ensureFile(draftsKeepPath, "");
    return;
  }

  if (existsSync(draftsKeepPath)) {
    unlinkSync(draftsKeepPath);
  }
}

export function ensureGitIgnoreEntries(projectRoot, entries) {
  const gitIgnorePath = path.join(projectRoot, ".gitignore");
  const existing = existsSync(gitIgnorePath) ? readFileSync(gitIgnorePath, "utf8") : "";
  const missingEntries = entries.filter((entry) => !existing.includes(entry));

  if (missingEntries.length === 0) {
    return false;
  }

  const nextSource = existing.trimEnd().length > 0 ? `${existing.trimEnd()}\n` : "";
  writeFileSync(gitIgnorePath, `${nextSource}${missingEntries.join("\n")}\n`, "utf8");
  return true;
}

export function createEmptyScene() {
  return {
    version: 1,
    meta: {
      zoom: 1,
      revision: 0,
      selectedStudyId: null,
    },
    nodes: [],
  };
}
