import type { AgentPickerComponentItem } from "@agent-picker/react/types";

// Generated by scripts/generate-agent-picker-page-imports.mjs. Do not edit manually.
export const generatedAgentPickerPageImportItems: AgentPickerComponentItem[] = [

];
